#!/usr/bin/env node
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.join(SCRIPT_DIR, '..');
const BYPASSES_DIR = path.join(REPO_ROOT, 'src', 'bypasses');
const OUTPUT_FILE = path.join(REPO_ROOT, 'web', 'src', 'data', 'supportedSites.ts');

function scanFiles(dir: string): string[] {
  const files: string[] = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...scanFiles(fullPath));
    } else if (entry.name.endsWith('.ts') && entry.name !== 'BypassDefinition.ts') {
      files.push(fullPath);
    }
  }

  return files;
}

function extractMatches(filePath: string): string[] {
  const content = fs.readFileSync(filePath, 'utf-8');
  const matchLine = content.match(/export\s+const\s+matches\s*=\s*\[([\s\S]*?)\]/);
  if (!matchLine) return [];

  return matchLine[1]
    .split(',')
    .map((entry) => entry.trim())
    .map((entry) => entry.replace(/^['"]|['"]$/g, '').trim())
    .filter(Boolean);
}

function normalizeDomain(match: string): string | null {
  const trimmed = match.trim();
  if (!trimmed || trimmed.includes('*')) return null;
  if (trimmed.startsWith('/') && trimmed.endsWith('/')) return null;

  const parseAsUrl = (value: string) => {
    try {
      return new URL(value).hostname || null;
    } catch {
      return null;
    }
  };

  if (/^https?:\/\//i.test(trimmed)) {
    return parseAsUrl(trimmed);
  }

  const hostCandidate = trimmed.split(/[/?#]/)[0];
  if (!hostCandidate || !hostCandidate.includes('.')) return null;
  if (!/^[a-z0-9.-]+$/i.test(hostCandidate)) return null;

  return hostCandidate.toLowerCase();
}

function buildOutput(domains: string[]) {
  const lines = domains.map((domain) => `  '${domain}',`).join('\n');
  return `// This file is generated by scripts/sync-supported-sites.ts. Do not edit manually.\nexport const supportedSites = [\n${lines}\n] as const;\n\nexport type SupportedSite = (typeof supportedSites)[number];\n`;
}

function main() {
  const domains = new Set<string>();

  for (const file of scanFiles(BYPASSES_DIR)) {
    for (const match of extractMatches(file)) {
      const domain = normalizeDomain(match);
      if (domain) domains.add(domain);
    }
  }

  const sortedDomains = [...domains].sort((a, b) => a.localeCompare(b));
  const output = buildOutput(sortedDomains);
  fs.mkdirSync(path.dirname(OUTPUT_FILE), { recursive: true });
  fs.writeFileSync(OUTPUT_FILE, output);
  console.log(`Wrote ${sortedDomains.length} supported domains to ${path.relative(REPO_ROOT, OUTPUT_FILE)}`);
}

main();
